export {default as Login} from './Auth/Login/Login'
export {default as Registration} from './Auth/Registration/Registration'
export {default as Multi} from './Charts/Chart/Multi'
export {default as Bar} from './Charts/Chart/Bar'
export {default as Charts} from './Charts/Charts'
export {default as Header} from './admin/Header/Header'
export {default as Main} from './Main/Main'
export {default as Sidebar} from './Sidebar/Sidebar'
export {default as TabsBlock} from './Tabs/Tabs'
export {default as Forms} from './Forms/Forms'
export {default as Tables} from './Tables/Tables'

